org: iainhoolahan
app: pfglambdas
service: pfg-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: iain_pfg
  region: eu-west-2
  environment:
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    EMAIL_TO: ${env:SENDGRID_VERIFIED_EMAIL}

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /test
          method: get
  sendEmail:
    handler: lib/sendEmail.handler
    events:
      - http:
          path: send-email
          method: post
          cors:
            origins:
              - 'http://www.pfgeomatics.com'
              - 'http://localhost:3000'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true